import JSZip from 'jszip'
import { resolvePublicAppUrl } from './public-app-url'

/**
 * Port of clean_manifests_.py — strips junk lines from the .lua file inside a
 * manifest zip, removes any prior attribution to upstream sources, and prepends
 * the OpenSteam credit header.
 *
 * Intended to be called at every entry point that produces a manifest zip
 * (upload + every upstream fetch) so the lua always carries our credit.
 */

function buildCredit(): string {
  const siteUrl = resolvePublicAppUrl()
  const displayUrl = siteUrl.includes('opensteam.lol') ? siteUrl : 'https://opensteam.lol'
  return [
    '-- ────────────────────────────────────────────────────────────',
    '--  Generated by OpenSteam',
    `--  ${displayUrl}`,
    '-- ────────────────────────────────────────────────────────────',
    ''
  ].join('\n')
}

const BANNED_FRAGMENTS = [
  // Twentytwo
  'twentytwo cloud',
  'twentytwo server',
  'redistribution of twentytwo',
  'discord.com/invite/vwgwetftxw',
  // Hubcap
  'hubcap manifest',
  'hubcapmanifest.com',
  // DepotBox
  'depotbox',
  'depotbox.org',
  'total depots:',
  'total dlcs:',
  'shared depots:',
]

const RE_FUNC_CALL = /^(addappid|setManifestid)\s*\(/i

function cleanLua(raw: string): string | null {
  const cleanedLines: string[] = []
  for (const line of raw.split(/\r?\n/)) {
    const stripped = line.trim()
    if (!stripped || stripped.startsWith('--')) continue
    const low = stripped.toLowerCase()
    if (BANNED_FRAGMENTS.some(frag => low.includes(frag))) continue
    if (!RE_FUNC_CALL.test(stripped)) continue
    // Trim trailing junk after the matching closing paren
    let parenDepth = 0
    let cutAt = stripped.length
    for (let i = 0; i < stripped.length; i++) {
      const ch = stripped[i]
      if (ch === '(') parenDepth++
      else if (ch === ')') {
        parenDepth--
        if (parenDepth === 0) {
          cutAt = i + 1
          break
        }
      }
    }
    let cleaned = stripped.slice(0, cutAt)
    // Normalize function name to canonical casing
    cleaned = cleaned.replace(/^addappid/i, 'addappid').replace(/^setmanifestid/i, 'setManifestid')
    cleanedLines.push(cleaned)
  }
  if (!cleanedLines.length || !cleanedLines.some(l => /^addappid\(/i.test(l))) {
    return null
  }
  return buildCredit() + cleanedLines.join('\n') + '\n'
}

/**
 * Returns a new zip buffer with the .lua inside rewritten + credited.
 * Falls back to the original buffer when:
 *   - The zip is unreadable (BadZipFile)
 *   - There is no .lua inside
 *   - The lua has no recognisable addappid()/setManifestid() calls
 *   - Cleaning otherwise fails
 *
 * Never throws — manifest delivery should not be blocked by a cleaning failure.
 */
export async function cleanManifestZip(input: Buffer): Promise<Buffer> {
  try {
    const zip = await JSZip.loadAsync(input)
    const luaNames = Object.keys(zip.files).filter(
      (n) => !zip.files[n].dir && n.toLowerCase().endsWith('.lua'),
    )
    if (luaNames.length === 0) return input

    let changed = false
    for (const luaName of luaNames) {
      const raw = await zip.file(luaName)!.async('string')
      const cleaned = cleanLua(raw)
      if (cleaned === null) continue
      if (raw.replace(/\r/g, '') === cleaned) continue
      zip.file(luaName, cleaned)
      changed = true
    }

    if (!changed) return input
    const out = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })
    return Buffer.from(out)
  } catch (e: any) {
    console.warn('[clean-manifest] failed, serving original:', e?.message)
    return input
  }
}
